local http = require "..http"

local app = http.new(8080)

app.static_dir = "./static"

app:get("/", function(self: *http.Server)
  return (@http.Response)({content = "hello"})
end)

app:get("/test/x", function(self: *http.Server)
  return (@http.Response)({content = "not x"})
end)
app:get("/test/x/y", function(self: *http.Server)
  return (@http.Response)({content = "not xy"})
end)
app:get("/test/x/y/z", function(self: *http.Server)
  return (@http.Response)({content = "not xyz"})
end)
app:get("/test/:x", function(self: *http.Server)
  return (@http.Response)({content = "bye " .. self.req.params["x"]})
end)
app:get("/test/:x/:y", function(self: *http.Server)
  return (@http.Response)({content = "bye " .. self.req.params["x"] .. self.req.params["y"]})
end)
app:get("/test/:x/:y/:z", function(self: *http.Server)
  return (@http.Response)({content = "bye " .. self.req.params["x"] .. self.req.params["y"] .. self.req.params["z"]})
end)

app:serve()
