local http = require "..http"

do
  local app = http.Server.new({
    log = http.TriBool.FALSE
  })

  app:get(nil, "/", function(self: *http.Server)
    local resp = self:text(200, "ok")
    local ok = resp:set_cookie({
      name = "name",
      val = "james"
    })
    assert(ok)
    assert(resp.cookies[1].name == "name")
    return resp
  end)

  app:mock_request("/")
end

do
  local app = http.Server.new()
  app.req.headers["Cookie"] = "name=james; age=10"

  local name = app.req:get_cookie("name")
  local age = app.req:get_cookie("age")
  assert(name == "james")
  assert(age == "10")
end
