local http = require("..http")

local app = http.new({
  logging = http.NotSetOrBool.FALSE
})

app:get(nil, "/", function(self: *http.Server)
  return self:text(http.Status.OK, "Hello world")
end)

do
  local str = "GET / HTTP/1.1\r\nHost: localhost\r\n\r\n"
  local resp_str = http.handle_request(str, &app)
  local formatted_date = os.date("%a, %d %b %Y %H:%M:%S GMT")
  local expected =
    ("HTTP/1.1 200 OK\r\nServer: http-nelua\r\nDate: %s\r\nContent-type: text/plain\r\nContent-Length: 13\r\n\r\nHello world\r\n")
      :format(formatted_date)
  assert(resp_str == expected)
  resp_str:destroy()
end

app:post(nil, "/", function(self: *http.Server)
  return self:text(http.Status.OK, ("%s %s"):format(self.req.params["username"], self.req.params["age"]))
end)

do
  local str =
    "POST / HTTP/1.1\r\nHost: localhost\r\nContent-Type: application/x-www-form-urlencoded\r\nContent-Length: 19\r\n\r\nusername=test&age=30"
  local resp_str = http.handle_request(str, &app)
  local formatted_date = os.date("%a, %d %b %Y %H:%M:%S GMT")
  local expected =
    ("HTTP/1.1 200 OK\r\nServer: http-nelua\r\nDate: %s\r\nContent-type: text/plain\r\nContent-Length: 9\r\n\r\ntest 30\r\n")
      :format(formatted_date)
  assert(resp_str == expected)
  resp_str:destroy()
end

app:get(nil, "/test", function(self: *http.Server)
  return self:text(http.Status.OK, ("%s %s"):format(self.req.params["name"], self.req.params["lang"]))
end)

do
  local str = "GET /test?name=nelua&lang=english HTTP/1.1\r\nHost: localhost\r\n\r\n"
  local resp_str = http.handle_request(str, &app)
  local formatted_date = os.date("%a, %d %b %Y %H:%M:%S GMT")
  local expected =
    ("HTTP/1.1 200 OK\r\nServer: http-nelua\r\nDate: %s\r\nContent-type: text/plain\r\nContent-Length: 15\r\n\r\nnelua english\r\n")
      :format(formatted_date)
  assert(resp_str == expected)
  resp_str:destroy()
end

app:get(nil, "/test/:id/:name", function(self: *http.Server)
  return self:text(http.Status.OK, ("%s %s"):format(self.req.params["id"], self.req.params["name"]))
end)

do
  local str = "GET /test/1/nelua HTTP/1.1\r\nHost: localhost\r\n\r\n"
  local resp_str = http.handle_request(str, &app)
  local formatted_date = os.date("%a, %d %b %Y %H:%M:%S GMT")
  local expected =
    ("HTTP/1.1 200 OK\r\nServer: http-nelua\r\nDate: %s\r\nContent-type: text/plain\r\nContent-Length: 9\r\n\r\n1 nelua\r\n")
      :format(formatted_date)
  assert(resp_str == expected)
  resp_str:destroy()
end

--[[
  Tests to write:
  - static files
  - invalid routes
  - POST,PUT,PATCH,DELETE requests
  - invalid request strings
]]
