local nttp = require "..nttp"

-- These tests are reliant on the network and would fail without one
-- This may not equate to the function not working correctly
do
  local result, err = nttp.send_request({
    url = "https://dummy-json.mock.beeceptor.com/posts/1",
    method = "get"
  })
  local expected = [[
{
    "userId": 1,
    "id": 1,
    "title": "Introduction to Artificial Intelligence",
    "body": "Learn the basics of Artificial Intelligence and its applications in various industries.",
    "link": "https://example.com/article1",
    "comment_count": 8
}]]
  assert(err == "", err)
  assert(result.status == "200")
  assert(result.body == expected)
end

do
  -- expected is too large so chosen to ignore it
  local result, err = nttp.send_request({
    url = "http://httpforever.com/",
    method = "get"
  })
  assert(err == "", err)
  assert(result.status == "200")
end

do
  -- chunked response test
  local result, err = nttp.send_request({
    url = "https://anglesharp.azurewebsites.net/Chunked",
    method = "get"
  })
  local expected = "<!DOCTYPE html>\r\n<html lang=en>\r\n<head>\r\n<meta charset='utf-8'>\r\n<title>Chunked transfer encoding test</title>\r\n</head>\r\n<body><h1>Chunked transfer encoding test</h1><h5>This is a chunked response after 100 ms.</h5><h5>This is a chunked response after 1 second. The server should not close the stream before all chunks are sent to a client.</h5></body></html>\r\n"
  assert(err == "", err)
  assert(result.status == "200")
  assert(result.body == expected)
end
