local nttp = require "..nttp"

do
  local app = nttp.Server.new({
    log = nttp.TriBool.FALSE
  })

  app:get(nil, "/", function(self: *nttp.Server)
    local name = self.session:get_val("name")
    local age = self.session:get_val("age")
    local home_town = self.session:get_val("home-town")
    assert(name == "james")
    assert(age == "10")
    assert(home_town == "new york")

    return self:text(200, "ok")
  end)

  app:mock_request("/", {
    session_vals = map!(string, string, {
      name = "james",
      age = "10",
      ["home-town"] = "new york"
    })
  })
end

do
  local app = nttp.Server.new({
    log = nttp.TriBool.FALSE
  })

  app:get(nil, "/", function(self: *nttp.Server)
    local name = self.session:get_val("name")
    local age = self.session:get_val("age")
    assert(name == "")
    assert(age == "")

    return self:text(200, "ok")
  end)

  app:mock_request("/")
end
