local http = require "..http"

do
  local app = http.Server.new({
    log = http.TriBool.FALSE
  })
  app:get(nil, "/", function(self: *http.Server)
    self.session:set_val("name", "james")
    self.session:set_val("age", "10")
    
    return self:text(200, "ok")
  end)

  app:get(nil, "/test", function(self: *http.Server)
    local name = self.session:get_val("name")
    local age = self.session:get_val("age")
    assert(name == "james")
    assert(age == "10")

    return self:text(200, "ok")
  end)

  
  app:mock_request("/")

  app:mock_request("/test", {
    session_vals = map!(string, string, {
      name = "james",
      age = "10"
    })
  })
end

do
  local app = http.Server.new({
    log = http.TriBool.FALSE
  })

  app:get(nil, "/test", function(self: *http.Server)
    local name = self.session:get_val("name")
    local age = self.session:get_val("age")
    assert(name == "")
    assert(age == "")

    return self:text(200, "ok")
  end)

  
  app:mock_request("/")
end
